//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test_service_ui.weight_record_service {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="weight_record_service.iweight_record_service")]
    public interface iweight_record_service {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iweight_record_service/getallweightsinservice", ReplyAction="http://tempuri.org/iweight_record_service/getallweightsinserviceResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(weight_recording_service_dal.service_fault), Action="http://tempuri.org/iweight_record_service/getallweightsinserviceservice_faultFaul" +
            "t", Name="service_fault", Namespace="http://schemas.datacontract.org/2004/07/weight_recording_service_dal")]
        System.Collections.Generic.List<weight_recording_service_dal.weight_record_dto> getallweightsinservice();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iweight_record_service/getallweightsinservice", ReplyAction="http://tempuri.org/iweight_record_service/getallweightsinserviceResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<weight_recording_service_dal.weight_record_dto>> getallweightsinserviceAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iweight_record_service/createweightinservice", ReplyAction="http://tempuri.org/iweight_record_service/createweightinserviceResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(weight_recording_service_dal.service_fault), Action="http://tempuri.org/iweight_record_service/createweightinserviceservice_faultFault" +
            "", Name="service_fault", Namespace="http://schemas.datacontract.org/2004/07/weight_recording_service_dal")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<weight_recording_service_dal.weight_record_dto>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(weight_recording_service_dal.weight_record_dto))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(weight_recording_service_dal.service_fault))]
        weight_recording_service_dal.responsedto createweightinservice(weight_recording_service_dal.weight_record_dto service_dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iweight_record_service/createweightinservice", ReplyAction="http://tempuri.org/iweight_record_service/createweightinserviceResponse")]
        System.Threading.Tasks.Task<weight_recording_service_dal.responsedto> createweightinserviceAsync(weight_recording_service_dal.weight_record_dto service_dto);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface iweight_record_serviceChannel : test_service_ui.weight_record_service.iweight_record_service, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class iweight_record_serviceClient : System.ServiceModel.ClientBase<test_service_ui.weight_record_service.iweight_record_service>, test_service_ui.weight_record_service.iweight_record_service {
        
        public iweight_record_serviceClient() {
        }
        
        public iweight_record_serviceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public iweight_record_serviceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public iweight_record_serviceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public iweight_record_serviceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<weight_recording_service_dal.weight_record_dto> getallweightsinservice() {
            return base.Channel.getallweightsinservice();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<weight_recording_service_dal.weight_record_dto>> getallweightsinserviceAsync() {
            return base.Channel.getallweightsinserviceAsync();
        }
        
        public weight_recording_service_dal.responsedto createweightinservice(weight_recording_service_dal.weight_record_dto service_dto) {
            return base.Channel.createweightinservice(service_dto);
        }
        
        public System.Threading.Tasks.Task<weight_recording_service_dal.responsedto> createweightinserviceAsync(weight_recording_service_dal.weight_record_dto service_dto) {
            return base.Channel.createweightinserviceAsync(service_dto);
        }
    }
}
