//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace weight_recording_dal.weight_record_service {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="weight_record_dto", Namespace="http://schemas.datacontract.org/2004/07/weight_recording_service_dal")]
    [System.SerializableAttribute()]
    public partial class weight_record_dto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string created_dateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string weight_appField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string weight_dateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string weight_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string weight_statusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string weight_weightField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string created_date {
            get {
                return this.created_dateField;
            }
            set {
                if ((object.ReferenceEquals(this.created_dateField, value) != true)) {
                    this.created_dateField = value;
                    this.RaisePropertyChanged("created_date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string weight_app {
            get {
                return this.weight_appField;
            }
            set {
                if ((object.ReferenceEquals(this.weight_appField, value) != true)) {
                    this.weight_appField = value;
                    this.RaisePropertyChanged("weight_app");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string weight_date {
            get {
                return this.weight_dateField;
            }
            set {
                if ((object.ReferenceEquals(this.weight_dateField, value) != true)) {
                    this.weight_dateField = value;
                    this.RaisePropertyChanged("weight_date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string weight_id {
            get {
                return this.weight_idField;
            }
            set {
                if ((object.ReferenceEquals(this.weight_idField, value) != true)) {
                    this.weight_idField = value;
                    this.RaisePropertyChanged("weight_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string weight_status {
            get {
                return this.weight_statusField;
            }
            set {
                if ((object.ReferenceEquals(this.weight_statusField, value) != true)) {
                    this.weight_statusField = value;
                    this.RaisePropertyChanged("weight_status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string weight_weight {
            get {
                return this.weight_weightField;
            }
            set {
                if ((object.ReferenceEquals(this.weight_weightField, value) != true)) {
                    this.weight_weightField = value;
                    this.RaisePropertyChanged("weight_weight");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="service_fault", Namespace="http://schemas.datacontract.org/2004/07/weight_recording_service_dal")]
    [System.SerializableAttribute()]
    public partial class service_fault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string messageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string message {
            get {
                return this.messageField;
            }
            set {
                if ((object.ReferenceEquals(this.messageField, value) != true)) {
                    this.messageField = value;
                    this.RaisePropertyChanged("message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="responsedto", Namespace="http://schemas.datacontract.org/2004/07/weight_recording_service_dal")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(weight_recording_dal.weight_record_service.weight_record_dto[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(weight_recording_dal.weight_record_service.weight_record_dto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(weight_recording_dal.weight_record_service.service_fault))]
    public partial class responsedto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool isresponseresultsuccessfulField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string responseclassField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string responseerrormessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string responsemethodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object responseresultobjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string responsesuccessmessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isresponseresultsuccessful {
            get {
                return this.isresponseresultsuccessfulField;
            }
            set {
                if ((this.isresponseresultsuccessfulField.Equals(value) != true)) {
                    this.isresponseresultsuccessfulField = value;
                    this.RaisePropertyChanged("isresponseresultsuccessful");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string responseclass {
            get {
                return this.responseclassField;
            }
            set {
                if ((object.ReferenceEquals(this.responseclassField, value) != true)) {
                    this.responseclassField = value;
                    this.RaisePropertyChanged("responseclass");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string responseerrormessage {
            get {
                return this.responseerrormessageField;
            }
            set {
                if ((object.ReferenceEquals(this.responseerrormessageField, value) != true)) {
                    this.responseerrormessageField = value;
                    this.RaisePropertyChanged("responseerrormessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string responsemethod {
            get {
                return this.responsemethodField;
            }
            set {
                if ((object.ReferenceEquals(this.responsemethodField, value) != true)) {
                    this.responsemethodField = value;
                    this.RaisePropertyChanged("responsemethod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object responseresultobject {
            get {
                return this.responseresultobjectField;
            }
            set {
                if ((object.ReferenceEquals(this.responseresultobjectField, value) != true)) {
                    this.responseresultobjectField = value;
                    this.RaisePropertyChanged("responseresultobject");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string responsesuccessmessage {
            get {
                return this.responsesuccessmessageField;
            }
            set {
                if ((object.ReferenceEquals(this.responsesuccessmessageField, value) != true)) {
                    this.responsesuccessmessageField = value;
                    this.RaisePropertyChanged("responsesuccessmessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="weight_record_service.iweight_record_service")]
    public interface iweight_record_service {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iweight_record_service/getallweightsinservice", ReplyAction="http://tempuri.org/iweight_record_service/getallweightsinserviceResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(weight_recording_dal.weight_record_service.service_fault), Action="http://tempuri.org/iweight_record_service/getallweightsinserviceservice_faultFaul" +
            "t", Name="service_fault", Namespace="http://schemas.datacontract.org/2004/07/weight_recording_service_dal")]
        weight_recording_dal.weight_record_service.weight_record_dto[] getallweightsinservice();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iweight_record_service/getallweightsinservice", ReplyAction="http://tempuri.org/iweight_record_service/getallweightsinserviceResponse")]
        System.Threading.Tasks.Task<weight_recording_dal.weight_record_service.weight_record_dto[]> getallweightsinserviceAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iweight_record_service/get_all_active_weights_in_service", ReplyAction="http://tempuri.org/iweight_record_service/get_all_active_weights_in_serviceRespon" +
            "se")]
        [System.ServiceModel.FaultContractAttribute(typeof(weight_recording_dal.weight_record_service.service_fault), Action="http://tempuri.org/iweight_record_service/get_all_active_weights_in_serviceservic" +
            "e_faultFault", Name="service_fault", Namespace="http://schemas.datacontract.org/2004/07/weight_recording_service_dal")]
        weight_recording_dal.weight_record_service.weight_record_dto[] get_all_active_weights_in_service();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iweight_record_service/get_all_active_weights_in_service", ReplyAction="http://tempuri.org/iweight_record_service/get_all_active_weights_in_serviceRespon" +
            "se")]
        System.Threading.Tasks.Task<weight_recording_dal.weight_record_service.weight_record_dto[]> get_all_active_weights_in_serviceAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iweight_record_service/createweightinservice", ReplyAction="http://tempuri.org/iweight_record_service/createweightinserviceResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(weight_recording_dal.weight_record_service.service_fault), Action="http://tempuri.org/iweight_record_service/createweightinserviceservice_faultFault" +
            "", Name="service_fault", Namespace="http://schemas.datacontract.org/2004/07/weight_recording_service_dal")]
        weight_recording_dal.weight_record_service.responsedto createweightinservice(weight_recording_dal.weight_record_service.weight_record_dto service_dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iweight_record_service/createweightinservice", ReplyAction="http://tempuri.org/iweight_record_service/createweightinserviceResponse")]
        System.Threading.Tasks.Task<weight_recording_dal.weight_record_service.responsedto> createweightinserviceAsync(weight_recording_dal.weight_record_service.weight_record_dto service_dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iweight_record_service/updateweightinservice", ReplyAction="http://tempuri.org/iweight_record_service/updateweightinserviceResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(weight_recording_dal.weight_record_service.service_fault), Action="http://tempuri.org/iweight_record_service/updateweightinserviceservice_faultFault" +
            "", Name="service_fault", Namespace="http://schemas.datacontract.org/2004/07/weight_recording_service_dal")]
        weight_recording_dal.weight_record_service.responsedto updateweightinservice(weight_recording_dal.weight_record_service.weight_record_dto service_dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iweight_record_service/updateweightinservice", ReplyAction="http://tempuri.org/iweight_record_service/updateweightinserviceResponse")]
        System.Threading.Tasks.Task<weight_recording_dal.weight_record_service.responsedto> updateweightinserviceAsync(weight_recording_dal.weight_record_service.weight_record_dto service_dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iweight_record_service/deleteweightinservice", ReplyAction="http://tempuri.org/iweight_record_service/deleteweightinserviceResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(weight_recording_dal.weight_record_service.service_fault), Action="http://tempuri.org/iweight_record_service/deleteweightinserviceservice_faultFault" +
            "", Name="service_fault", Namespace="http://schemas.datacontract.org/2004/07/weight_recording_service_dal")]
        weight_recording_dal.weight_record_service.responsedto deleteweightinservice(weight_recording_dal.weight_record_service.weight_record_dto service_dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iweight_record_service/deleteweightinservice", ReplyAction="http://tempuri.org/iweight_record_service/deleteweightinserviceResponse")]
        System.Threading.Tasks.Task<weight_recording_dal.weight_record_service.responsedto> deleteweightinserviceAsync(weight_recording_dal.weight_record_service.weight_record_dto service_dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iweight_record_service/delete_weight_by_changing_status_in_ser" +
            "vice", ReplyAction="http://tempuri.org/iweight_record_service/delete_weight_by_changing_status_in_ser" +
            "viceResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(weight_recording_dal.weight_record_service.service_fault), Action="http://tempuri.org/iweight_record_service/delete_weight_by_changing_status_in_ser" +
            "viceservice_faultFault", Name="service_fault", Namespace="http://schemas.datacontract.org/2004/07/weight_recording_service_dal")]
        weight_recording_dal.weight_record_service.responsedto delete_weight_by_changing_status_in_service(weight_recording_dal.weight_record_service.weight_record_dto service_dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iweight_record_service/delete_weight_by_changing_status_in_ser" +
            "vice", ReplyAction="http://tempuri.org/iweight_record_service/delete_weight_by_changing_status_in_ser" +
            "viceResponse")]
        System.Threading.Tasks.Task<weight_recording_dal.weight_record_service.responsedto> delete_weight_by_changing_status_in_serviceAsync(weight_recording_dal.weight_record_service.weight_record_dto service_dto);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface iweight_record_serviceChannel : weight_recording_dal.weight_record_service.iweight_record_service, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class iweight_record_serviceClient : System.ServiceModel.ClientBase<weight_recording_dal.weight_record_service.iweight_record_service>, weight_recording_dal.weight_record_service.iweight_record_service {
        
        public iweight_record_serviceClient() {
        }
        
        public iweight_record_serviceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public iweight_record_serviceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public iweight_record_serviceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public iweight_record_serviceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public weight_recording_dal.weight_record_service.weight_record_dto[] getallweightsinservice() {
            return base.Channel.getallweightsinservice();
        }
        
        public System.Threading.Tasks.Task<weight_recording_dal.weight_record_service.weight_record_dto[]> getallweightsinserviceAsync() {
            return base.Channel.getallweightsinserviceAsync();
        }
        
        public weight_recording_dal.weight_record_service.weight_record_dto[] get_all_active_weights_in_service() {
            return base.Channel.get_all_active_weights_in_service();
        }
        
        public System.Threading.Tasks.Task<weight_recording_dal.weight_record_service.weight_record_dto[]> get_all_active_weights_in_serviceAsync() {
            return base.Channel.get_all_active_weights_in_serviceAsync();
        }
        
        public weight_recording_dal.weight_record_service.responsedto createweightinservice(weight_recording_dal.weight_record_service.weight_record_dto service_dto) {
            return base.Channel.createweightinservice(service_dto);
        }
        
        public System.Threading.Tasks.Task<weight_recording_dal.weight_record_service.responsedto> createweightinserviceAsync(weight_recording_dal.weight_record_service.weight_record_dto service_dto) {
            return base.Channel.createweightinserviceAsync(service_dto);
        }
        
        public weight_recording_dal.weight_record_service.responsedto updateweightinservice(weight_recording_dal.weight_record_service.weight_record_dto service_dto) {
            return base.Channel.updateweightinservice(service_dto);
        }
        
        public System.Threading.Tasks.Task<weight_recording_dal.weight_record_service.responsedto> updateweightinserviceAsync(weight_recording_dal.weight_record_service.weight_record_dto service_dto) {
            return base.Channel.updateweightinserviceAsync(service_dto);
        }
        
        public weight_recording_dal.weight_record_service.responsedto deleteweightinservice(weight_recording_dal.weight_record_service.weight_record_dto service_dto) {
            return base.Channel.deleteweightinservice(service_dto);
        }
        
        public System.Threading.Tasks.Task<weight_recording_dal.weight_record_service.responsedto> deleteweightinserviceAsync(weight_recording_dal.weight_record_service.weight_record_dto service_dto) {
            return base.Channel.deleteweightinserviceAsync(service_dto);
        }
        
        public weight_recording_dal.weight_record_service.responsedto delete_weight_by_changing_status_in_service(weight_recording_dal.weight_record_service.weight_record_dto service_dto) {
            return base.Channel.delete_weight_by_changing_status_in_service(service_dto);
        }
        
        public System.Threading.Tasks.Task<weight_recording_dal.weight_record_service.responsedto> delete_weight_by_changing_status_in_serviceAsync(weight_recording_dal.weight_record_service.weight_record_dto service_dto) {
            return base.Channel.delete_weight_by_changing_status_in_serviceAsync(service_dto);
        }
    }
}
